language: python

env:
  - DRASH_DIR_ROOT="/home/travis/build/crookse/deno-drash" DRASH_CORE_LOGGER_ENABLED=false

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.3.6
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - console/tests
