language: python

env:
  - DRASH_DIR_ROOT="/home/travis/build/crookse"

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - console/test
