language: python

env:
  - DRASH_DIR_ROOT="/home/travis/build/crookse/deno-drash"
    VER_DENO_LATEST="0.22.0"
    VER_DENO_STD_LATEST="0.20.0"
    VER_DRASH_LATEST="0.22.2"

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.22.0
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - console/tests

deploy:
  - provider: script
    skip_cleanup: true
    script: console/deploy_docs
    on:
      tags: true
