language: python

python:
  - "3.6"

env:
  - VER_DENO_LATEST="0.28.0"

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v$VER_DENO_LATEST
  - export PATH="$HOME/.local/bin:$PATH" #make sure deno is accessible

script:
  - console/tests
