language: python

env:
  - VER_DENO_LATEST="0.22.0"
    VER_DENO_STD_LATEST="0.20.0"
    VER_DRASH_LATEST="0.22.2"

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v$VER_DENO_LATEST
  - export PATH="$HOME/.deno/bin:$PATH" #make sure deno is accessible

script:
  - console/tests

before_deploy:
  - cd $DRASH_DIR_ROOT
  - console/bump_versions
  - cd docs
  - npm install
  - export DRASH_DIR_EXAMPLE_CODE="$DRASH_DIR_ROOT/docs/src/example_code"
  - export DRASH_SERVER_DIRECTORY="$DRASH_DIR_ROOT/docs"
  - deno --allow-read --allow-write --allow-env --allow-net $DRASH_DIR_ROOT/docs/docs.ts
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

deploy:
  - provider: script
    skip_cleanup: true
    script: console/deploy
    on:
      tags: true

after_deploy:
  - cd $DRASH_DIR_ROOT/docs
  - git add index.html
  - git add public/assets/js/bundle.min.js
  - git commit -m "npm run build ($(date))"
  - git push https://$GIT_USER:$GIT_PASSWORD@github.com/crookse/deno-drash.git HEAD:$BRANCH
