language: python

env:
  - DRASH_DIR_ROOT="/home/travis/build/crookse/deno-drash"

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.20.0
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - console/tests

deploy:
  - provider: script
    skip_cleanup: true
    script: cd $DRASH_DIR_ROOT/docs && npm run docs-deploy
    on:
      tags: true
