name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    env:
      CI: true
      CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      CI_USER_PAT: ${{ secrets.CI_USER_PAT }}
      DENO_INSTALL: "/Users/runner/.local"

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: install deno
      run: |
        console/install_deno

    - name: unit tests
      run: |
        export PATH=$DENO_INSTALL/bin:$PATH
        console/tests

    - name: deno format check
      run: |
        export PATH=$DENO_INSTALL/bin:$PATH
        deno fmt --check
